services:
  fabric:
    build: .
    container_name: minecraft-fabric-server
    environment:
      - MINECRAFT_VERSION=1.21.10
      - FABRIC_LOADER_VERSION=0.18.1
      - INSTALLER_VERSION=1.1.0
      - MAX_MEMORY=4G
    ports:
      - "25565:25565"
    volumes:
      - ./data:/server
    restart: unless-stopped
